feat(action): remove some useless action and update dockerfile

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,17 +10,28 @@ on:
         type: string
 
 jobs:
-  Install-Python-Dependency:
-    uses: ./.github/workflows/install_python_dependency.yml
-    secrets: inherit
   Build:
-    needs: Install-Python-Dependency
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ inputs.python_version }}
+  
+      - name: Check if Python is installed and exit if not
+        run: |
+            python_version=(${{ inputs.python_version }})
+            for version in "${python_version[@]}"; do
+              if ! command -v python$version &> /dev/null; then
+                echo "Python $version could not be found"
+                exit 1
+              fi
+            done
 
       - name: Install uv
         run: pip install uv
diff --git a/.github/workflows/lint_test.yml b/.github/workflows/lint_test.yml
--- a/.github/workflows/lint_test.yml
+++ b/.github/workflows/lint_test.yml
@@ -6,7 +6,7 @@ on:
       python_version:
         description: "Python version to use"
         required: true
-        default: "3"
+        default: "3.12"
         type: string
 
 jobs:
@@ -24,6 +24,22 @@ jobs:
           fetch-depth: 0
             # Install uv
           # Purpose: uv is a dependency manager and tool for managing Python projects.
+
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ inputs.python_version }}
+
+      - name: Check if Python is installed and exit if not
+        run: |
+            python_version=(${{ inputs.python_version }})
+            for version in "${python_version[@]}"; do
+              if ! command -v python$version &> /dev/null; then
+                echo "Python $version could not be found"
+                exit 1
+              fi
+            done
+
       - name: Create env file
         run: |
             echo "COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}" >> $PWD/.env
diff --git a/.github/workflows/workflow_commit_linter.yml b/.github/workflows/workflow_commit_linter.yml
--- a/.github/workflows/workflow_commit_linter.yml
+++ b/.github/workflows/workflow_commit_linter.yml
@@ -6,7 +6,7 @@ on:
       node_version:
         description: 'Node.js version to use'
         required: false
-        default: '14'
+        default: '21'
         type: string
 
 jobs:
@@ -19,6 +19,21 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ inputs.node_version }}
+
+      - name: Check if Node.js is installed and exit if not
+        run: |
+          node_version=(${{ inputs.node_version }})
+          for version in "${node_version[@]}"; do
+            if ! command -v node$version &> /dev/null; then
+              echo "Node.js $version could not be found"
+              exit 1
+            fi
+          done
+
       - name: Install commitlint
         run: |
           npm install conventional-changelog-conventionalcommits
@@ -29,5 +44,9 @@ jobs:
         run: npx commitlint --last --verbose
 
       - name: Validate PR commits with commitlint
-        if: github.event_name == 'pull_request'
+        if: github.event_name == 'pull_request'  && (github.event.action == 'opened' || github.event.action == 'synchronize')
         run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
+      
+      - name: Validate closed PR commits with commitlint
+        if: github.event_name == 'pull_request' && github.event.action == 'closed'
+        run: npx commitlint --from ${{ github.event.pull_request.head.sha }} --to ${{ github.event.pull_request.base.sha }} --verbose
