feat(action): refacto github action (more efficient)

diff --git a/.github/workflows/initialize_linux_env.yml b/.github/workflows/initialize_linux_env.yml
--- a/.github/workflows/initialize_linux_env.yml
+++ b/.github/workflows/initialize_linux_env.yml
@@ -30,28 +30,28 @@ jobs:
 
       - name: Setup Environment
         run: |
-            # Process the input commands
-            commands=$(echo '${{ inputs.commands }}' | sed 's/\[//g' | sed 's/\]//g' | tr ',' '\n' | sed 's/\"//g' | sed 's/^ *//g' | sed 's/ *$//g')
+          # Process the input commands
+          commands=$(echo '${{ inputs.commands }}' | sed 's/\[//g' | sed 's/\]//g' | tr ',' '\n' | sed 's/\"//g' | sed 's/^ *//g' | sed 's/ *$//g')
 
-            # Print the commands to be executed
-            echo "Commands to be executed:"
-            echo "$commands"
+          # Print the commands to be executed
+          echo "Commands to be executed:"
+          echo "$commands"
 
-            # Execute each command
-            while IFS= read -r cmd; do
-              if [ -n "$cmd" ]; then
-                echo "Executing: $cmd"
-                eval "$cmd"
-                if [ $? -ne 0 ]; then
-                  echo "Command failed: $cmd"
-                  exit 1
-                  fi
-              fi
-            done <<< "$commands"
+          # Execute each command
+          while IFS= read -r cmd; do
+            if [ -n "$cmd" ]; then
+              echo "Executing: $cmd"
+              eval "$cmd"
+              if [ $? -ne 0 ]; then
+                echo "Command failed: $cmd"
+                exit 1
+                fi
+            fi
+          done <<< "$commands"
       - name: Print versions
         run: |
           version_commands=$(echo '${{ inputs.version_commands }}' | sed 's/\[//g' | sed 's/\]//g'| tr ',' '\n' | sed 's/\"//g' | sed 's/^ *//g' | sed 's/ *$//g')
-           # Execute each command
+          # Execute each command
             while IFS= read -r cmd; do
               if [ -n "$cmd" ]; then
                 echo "Executing: $cmd"
