feat(action): create build action, remove useless github action (#16)
update api to set port according to dockerfile

diff --git a/.github/workflows/lint_test.yml b/.github/workflows/lint_test.yml
--- a/.github/workflows/lint_test.yml
+++ b/.github/workflows/lint_test.yml
@@ -6,16 +6,11 @@ on:
       python_version:
         description: "Python version to use"
         required: true
-        default: "3"
+        default: "3.12"
         type: string
 
 jobs:
-  Install-Python-Dependency:
-    uses: ./.github/workflows/install_python_dependency.yml
-    secrets: inherit
-
   Lint-test:
-    needs: Install-Python-Dependency
     runs-on: ubuntu-latest
     steps:
       - name: Checkcout Code
@@ -24,6 +19,22 @@ jobs:
           fetch-depth: 0
             # Install uv
           # Purpose: uv is a dependency manager and tool for managing Python projects.
+
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ inputs.python_version }}
+
+      - name: Check if Python is installed and exit if not
+        run: |
+            python_version=(${{ inputs.python_version }})
+            for version in "${python_version[@]}"; do
+              if ! command -v python$version &> /dev/null; then
+                echo "Python $version could not be found"
+                exit 1
+              fi
+            done
+
       - name: Create env file
         run: |
             echo "COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}" >> $PWD/.env
@@ -37,7 +48,7 @@ jobs:
       - name: Install dependencies and create virtual environment
         run: uv sync 
 
-      # Run linter (flake8)²
+      # Run linter (flake8)
       # Purpose: Run the flake8 linter on the project. The linter checks for PEP8 compliance.
       - name: Run linter (flake8)
         run: uv run flake8 --max-line-length=120 $GITHUB_WORKSPACE/api
